### ISSUE TITLE
Great Project

### ISSUE THREAD

**Issue by lganzzzo** [aogaki/VacMonServer#1]
Hello @aogaki ,

I was searching for oatpp + mongodb use-cases and I was happy to find your project!

We have recently released the new [oatpp-mongo](https://github.com/oatpp/oatpp-mongo) module with the DTO-BSON mapper, and it would be cool if you could find some time to try it (in this, on in your next projects). 
And I would be happy to help in case of any questions!

Also, please feel free to ping me in case of any questions about oatpp, or if you need a code review.

Best Regards,
Leonid

**Comment by aogaki** [comment]
Hello @lganzzzo ,


Now I checked the oatpp-mongo project.  No external dependencies is absolutely nice for me.  I am planning to build a experiment log web service for me and colleagues.  After a few months, probably, I will try to use in such the project. 

This project is already running and giving us a stable API server by Oat++.  I do not want a big change.  Thus it is difficult to try in this project now.

I really want to say thank you for you and your project.  I am looking forward to use the oatpp-mongo.


Best regards,
And please be healthy and far from virus.
Aogaki

**Comment by lganzzzo** [comment]
Hey, 

Thanks for the reply!
Sure, stability first.
The log server project sounds great!

Please feel free to reach out, in case of any questions.

Best Regards,
Leonid
